### ISSUE TITLE
Update: Sorted - How have yous made the cooling fan to work??? and Bluetooth?

### ISSUE THREAD

**Issue by DarkevilPT** [openFyde/overlay-rock5b-openfyde#2]
Yes because... OpenFyde via CroS VM doesnt give much utility to the radxa fan heatsink.
What is the work/around by that??

Second problem is... can we use linux to fix bluetooth?

**Comment by DarkevilPT** [comment]
Its the A8 Module the oficial Radxa One.
These are the steps required on Linux to make the A8 Module BT to Work:

`nano /etc/modprobe.d/blacklist.conf`
then add these lines somewhere (at the bottom of the file is fine):
```
blacklist btusb
blacklist btrtl
blacklist btbcm
blacklist btintel
```
Then press Ctrl+X, then Y.

`apt install bluez` or bluetooth
`systemctl status bluetooth` CTRL+ C
`systemctl start bluetooth`
Then `reboot`.
 https://github.com/armbian/build/pull/4541

And the fan heatsink is also the one from allnet and can be activated with
these:

Fan Control:
`git clone https://github.com/pymumu/fan-control-rock5b`
`cd fan-control-rock5b`
`make package`
`sudo dpkg -i fan-control*.deb`
`systemctl enable fan-control`
`systemctl start fan-control`

The issue is that after a few minutes testing the system it resets... I
managed to update the system on linux and make package for the fan and then
enable and starting it but in real time nothing happens... It simply doesnt
work...and the system reboots. I cant use it.. maybe the heat or the power
pd issue maybe.

Im using the samsung 45w super fast charger which has been working on other
distros...
I dont know.

**Comment by Damenly** [comment]
For bluetooth, would you please provide output of `lsmod` after `reboot`?
For fan heatsink, it seems workable to move the repo code to our repo.
Note: the application linux terminal is in VM. All changes in Debian VM won't influence the host. 

Your charger sounds fine, would system reboot when doing light works(open pages/watch videos in chromium)?

**Comment by DarkevilPT** [comment]
I have to do it after work.. Now I cant test it.
But yes please make the fan to work at least would buy me time to check the
temperatures for a more clean vision of whats going on and then would also
buy me time to check the bluetooth case which I think it could be fixable.

And by the way Damenly the Operative System is REALLLY REALLY GOOD ! SUPER
WELL OPTIMISED ! The best so far. Its user friendly and exactly what I
wanted. I got so excited when I saw all my favourites pinned webapps
bookmarks showing up that it was magic !

After work I will do what you asked me and send you.

**Comment by Damenly** [comment]
BTW, would you please run `apt install stress` and `sudo stress --cpu 8 -v` without fan heatsink in official Debian? 
Running both `stress` and `aquarium with 30000 fishes` in openFyde doesn't cause reboot on my side even the highest temperature is 85 celsius.

**Comment by DarkevilPT** [comment]
> BTW, would you please run `apt install stress` and `sudo stress --cpu 8 -v` without fan heatsink in official Debian? Running both `stress` and `aquarium with 30000 fishes` in openFyde doesn't cause reboot on my side even the highest temperature is 85 celsius.

As for this I believe its all a matter of not using my screen stand hub.. probably this is the reason why it keeps rebooting.. I wished this works fine out

**Comment by DarkevilPT** [comment]
> BTW, would you please run `apt install stress` and `sudo stress --cpu 8 -v` without fan heatsink in official Debian? Running both `stress` and `aquarium with 30000 fishes` in openFyde doesn't cause reboot on my side even the highest temperature is 85 celsius.

As for this second request well... I installed debian oficial image and couldnt see any wifi option and for ethernet I cant have it for now So I went back to a custom image.

Many have complained about the power supply I believe it can be it... However when when I was using OpenFyde with youtube running on the background and then discord the system would just reset out of nothing...

May I ask: Whats your Power Supply? Do you have the Rock 5B latest version or the test version? (1.42 rev).

Also: The A8 Module warms... really but really hot...
Also: I am not the only one with these issues claiming no bluetooth and reset issues : https://forum.radxa.com/t/openfyde-chromium-os-fork-for-rock-5b/10963/33

Actual status for me is: Impossible to use as it simply resets itself randomly. I doubt its the cpu temperatures as it rarely stepped over 51C it keeps it stable 48C 51C.
I was able to view these with an app that OpenFyde auto brought.

Also: I couldnt run Gapps I can install it but after pressing run theres an message claiming ' You dont have android activated please accept the terms' and this label doesnt go away to actually press acept and verify.
(Unless it is that first gmail accept terms via browser idk).
Even so I think I did and it still was showing. (Theres something there).

I like this OS it is made for me its super well optimised easy and looks literally what Android OS should be IMO
cause applying launchers for TV is what the google store has for plenty... but for the PC the duo between the best of both Worlds only OpenFyde provides.

- Heatsink fan (Not spinning)
- A8 Module (overheats and no bluetooth drivers maybe?)
- Random Reboots Resets screen goes dark the on to the login menu).
- Youtube + some other app reset.
- If you want a quick reset... try google remote desktop its magic as soon someone joins your session which makes a clear statement on the wifi module being probably the issue.

Please give us the working version I really want to start using OpenFyde without hassle.

**Comment by Damenly** [comment]
> > BTW, would you please run `apt install stress` and `sudo stress --cpu 8 -v` without fan heatsink in official Debian? Running both `stress` and `aquarium with 30000 fishes` in openFyde doesn't cause reboot on my side even the highest temperature is 85 celsius.
> 
> As for this second request well... I installed debian oficial image and couldnt see any wifi option and for ethernet I cant have it for now So I went back to a custom image.
> 
> Many have complained about the power supply I believe it can be it... However when when I was using OpenFyde with youtube running on the background and then discord the system would just reset out of nothing...
> 
That's the reason why I wished you do some `stress` tests to exclude potential power supply issue.
 
> May I ask: Whats your Power Supply? Do you have the Rock 5B latest version or the test version? (1.42 rev).
> 
An unofficial 65W Power Supply. Early 1.3 version.

> Also: The A8 Module warms... really but really hot... Also: I am not the only one with these issues claiming no bluetooth and reset issues : https://forum.radxa.com/t/openfyde-chromium-os-fork-for-rock-5b/10963/33
> 
Noticed. 

> Actual status for me is: Impossible to use as it simply resets itself randomly. I doubt its the cpu temperatures as it rarely stepped over 51C it keeps it stable 48C 51C. I was able to view these with an app that OpenFyde auto brought.
> 
> Also: I couldnt run Gapps I can install it but after pressing run theres an message claiming ' You dont have android activated please accept the terms' and this label doesnt go away to actually press acept and verify. (Unless it is that first gmail accept terms via browser idk). Even so I think I did and it still was showing. (Theres something there).
> 
> I like this OS it is made for me its super well optimised easy and looks literally what Android OS should be IMO cause applying launchers for TV is what the google store has for plenty... but for the PC the duo between the best of both Worlds only OpenFyde provides.
> 
Android OS is not landed in openFyde for now. It'll be in openFyde.

> * Heatsink fan (Not spinning)
> * A8 Module (has wifi but overheats and no bluetooth drivers maybe?)
My Heatsink fan  and A8 Module are on the way.

> * Random Reboots resets the screen it goes dark then on to the login menu).
> * Youtube + some other app reset.
> * Probably old dts configurations..
Kernel and DTS files are sync with Radxa branch. So...

> * If you want a quick reset... try google remote desktop its magic as soon someone joins your session which makes a clear statement on the wifi module being probably the issue.
> 
> Please give us the working version I really want to start using OpenFyde without hassle.
Sure. Thanks for your efforts. I'll test and reply once my modules are delivered.

**Comment by Damenly** [comment]
I have figured out why A8 Bluetooth is unable. The fix will be included in the next release.

For the fan heatsink, you can log in the host [this way](https://faq.fydeos.com/en/getting-started/shell-access/) and then call 
```
echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/export 
echo 10000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/period 
echo 5000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/duty_cycle 
echo normal > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/polarity 
echo 1 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable 
#echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable
```
Then you can exercise your rock5 in openFyde to avoid high temperatures.

**Comment by DarkevilPT** [comment]
Hell Yeah ! But any chance yous add an settings option for the fan (to turn
on)?

Also... this little board can perform on 64bits Ive been told often
OpenFyde is running on 32bits (This is more like an question for the
future) Would u see an OpenFyde 64bits ready in the future for us ?

**Comment by DarkevilPT** [comment]
> I have figured out why A8 Bluetooth is unable. The fix will be included in the next release.
> 
> For the fan heatsink, you can log in the host [this way](https://faq.fydeos.com/en/getting-started/shell-access/) and then call
> 
> ```
> echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/export 
> echo 10000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/period 
> echo 5000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/duty_cycle 
> echo normal > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/polarity 
> echo 1 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable 
> #echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable
> ```
> 
> Then you can exercise your rock5 in openFyde under proper temperatures.

Yes I can confirm that the fan spins but OpenFyde keeps freezing and crashing.

**Comment by Damenly** [comment]
> Hell Yeah ! But any chance yous add an settings option for the fan (to turn on)? 
 
I’ll add a daemon service to control the fan speed.

Also... this little board can perform on 64bits Ive been told often that OpenFyde is limited to run on 32bits (This is more like a question for the future) Would u see an OpenFyde 64bits ready in the future for us ?

It’s in our plans. As for now, kernel is 64bits and userspace is 32bits. So your 16 GB memory is fully used by kernel. In most scenarios you can’t detect differences from 32bits and 64bits. 
> […](#)

**Comment by Damenly** [comment]
> > I have figured out why A8 Bluetooth is unable. The fix will be included in the next release.
> > For the fan heatsink, you can log in the host [this way](https://faq.fydeos.com/en/getting-started/shell-access/) and then call
> > ```
> > echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/export 
> > echo 10000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/period 
> > echo 5000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/duty_cycle 
> > echo normal > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/polarity 
> > echo 1 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable 
> > #echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then you can exercise your rock5 in openFyde under proper temperatures.
> 
> Yes I can confirm that the fan spins but OpenFyde keeps freezing and crashing.

Can’t reproduce it. I’m afraid that you have to do stress tests in other OSs. If it’s only in openfyde then it’s time to fetch logs.

**Comment by DarkevilPT** [comment]
> > > I have figured out why A8 Bluetooth is unable. The fix will be included in the next release.
> > > For the fan heatsink, you can log in the host [this way](https://faq.fydeos.com/en/getting-started/shell-access/) and then call
> > > ```
> > > echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/export 
> > > echo 10000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/period 
> > > echo 5000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/duty_cycle 
> > > echo normal > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/polarity 
> > > echo 1 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable 
> > > #echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Then you can exercise your rock5 in openFyde under proper temperatures.
> > 
> > 
> > Yes I can confirm that the fan spins but OpenFyde keeps freezing and crashing.
> 
> Can’t reproduce it. I’m afraid that you have to do stress tests in other OSs. If it’s only in openfyde then it’s time to fetch logs.

Unless its my bluetooth dongle mouse making it Im gonna try now with the mouse wired before going into debian for stress tests

**Comment by DarkevilPT** [comment]
Stress test done on OpenFyde Diagnostics about_system.zip
The mouse ive tried with cable and OpenFyde doesnt detect it.
So I have plugged the dongle to USB 2.0 entrance instead of 3.0 and yes so
far no resets.. but.. its 1 am and tomorrow I will run a few more heavier
tasks to see. (I guess bluetooth dongles are messing)

**Comment by Damenly** [comment]
I've looked through the log. Nothing suspicious was found.

**Comment by DarkevilPT** [comment]
Here Damenly Su,

Debian oficial stress test and fish tank 3000 >
https://i.ibb.co/qgSFwcp/Screenshot-2023-01-08-09-24-59.png
Runs perfect no crashesits just on OpenFyde. Either is my wireless mouse
messing with the bluetooth A8 module making it crash or your test version
that works better than the 1.42 I dont know at this point.
Anyway... Im going back to the ubunto image... until OpenFyde next release.

**Comment by DarkevilPT** [comment]
I have no luck with openfyde.. It just freezes.
https://youtu.be/KTYu1LVDkhc

**Comment by DarkevilPT** [comment]
Update > Finally Sort out this ISSUE! FINALLY!!
Auff what a relief! 

RKDEVTOOLS you guys really need to make it more clearer on how to flash this.

My issue was that, because on my first attempt it failed to do the Download Image (tab) I was just doing Firmware Upgrade (Tab) and for some reason it never worked decent.

So here it goes and I hope this help the community because I love this!

At least for some clarity  on Windows:
RK Dev Tools: https://wiki.radxa.com/Rock5/install/rockchip-flash-tools
The files for RK Dev Tools are here: https://wiki.radxa.com/Rock5/install/spi
(You need the loader.bin and the Release.img)

I suggest everyone to do an SPI update with those files up aiming for the release.img
Theres a SPI config file in RKDevTools paste to Swap between EMMC and SPI.
SPI requires a SPI BIN file and the IMG file.  (both on the links above each for what type of usage you desire in my case EMMC). Release is for a default standard (Do Flash your SPI for a boot in EMMC then Micro SD if nothing then NVME).

Before yous say (this has nothing to do with flashing openfyde) well yes but for someone who does a lot of image swapping and to give a fresh install you better reset the boot spi flashing it via emmc right on RKDEVTOOLS or skip this part where the next one was the deal breaker for me.

RkDevTools has first a Download Image tab (because for me the first time I have used it / it failed to enter the maskmode I thought the mask mode button on Rock5B was the second button.. it detects something but its not the maskmode.
The maskmode button is beside the CPU on a top left corner in line with the type C connector.
Meaning that everytime RkDevTools fails u better close it and open (again the windows app) and enter into mask mode again by unplugging and plugging the typeC cable.

Here we go:
Download Image you will need RK Dev Tool.BIN file (found here https://wiki.radxa.com/Rock5/install/spi)
Second file to add is the image.IMG file which will be the OpenFyde OS image from github (Tutorial how to do RkDevTool also here https://wiki.radxa.com/Rock5/install/usb-install-emmc)

Check option Write by address then Press run. After done unplug type C.

We are not done yet.

Next - Second tab the Firmware Upgrade.
Get into maskmode - Load firmware.img from openfyde github wait - Then Flash. 
After its done unplug type C et voilá!! OpenFyde works nay!

---------------

For the fan to work ctrl alt T type Shell then sudo su -u
echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/export 
echo 10000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/period 
echo 5000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/duty_cycle 
echo normal > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/polarity 
echo 1 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable 
#echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable

Runs really slow... it should run a bit stronger for heavier duty to cooldown. 

Now known Issues:
Bluetooth support is coming on the next patch.
-No google apps support yet.

Thanks Damenly.

**Comment by Damenly** [comment]
> Update > Finally Sort out this ISSUE! FINALLY!! Auff what a relief!
>
 
Wooo!

> RKDEVTOOLS you guys really need to make it more clearer on how to flash this.
> 

Right.  It's our responsibility.  It's pretty awful to waste users' time to fash and disappoint them. 
The excuse is that most of us use linux tool not Windows RKDEVTOOLS. 
Anyway, We will make it clearer.

> My issue was that, because on my first attempt it failed to do the Download Image (tab) I was just doing Firmware Upgrade (Tab) and for some reason it never worked decent.
> 
> So here it goes and I hope this help the community because I love this!
> 

Thanks for your detailed steps.
> At least for some clarity on Windows: RK Dev Tools: https://wiki.radxa.com/Rock5/install/rockchip-flash-tools The files for RK Dev Tools are here: https://wiki.radxa.com/Rock5/install/spi (You need the loader.bin and the Release.img)
> 
> I suggest everyone to do an SPI update with those files up aiming for the release.img Theres a SPI config file in RKDevTools paste to Swap between EMMC and SPI. SPI requires a SPI BIN file and the IMG file. (both on the links above each for what type of usage you desire in my case EMMC). Release is for a default standard (Do Flash your SPI for a boot in EMMC then Micro SD if nothing then NVME).
> 
> Before yous say (this has nothing to do with flashing openfyde) well yes but for someone who does a lot of image swapping and to give a fresh install you better reset the boot spi flashing it via emmc right on RKDEVTOOLS or skip this part where the next one was the deal breaker for me.
> 
> RkDevTools has first a Download Image tab (because for me the first time I have used it / it failed to enter the maskmode I thought the mask mode button on Rock5B was the second button.. it detects something but its not the maskmode. The maskmode button is beside the CPU on a top left corner in line with the type C connector. Meaning that everytime RkDevTools fails u better close it and open (again the windows app) and enter into mask mode again by unplugging and plugging the typeC cable.
> 
> Here we go: Download Image you will need RK Dev Tool.BIN file (found here https://wiki.radxa.com/Rock5/install/spi) Second file to add is the image.IMG file which will be the OpenFyde OS image from github (Tutorial how to do RkDevTool also here https://wiki.radxa.com/Rock5/install/usb-install-emmc)
> 
> Check option Write by address then Press run. After done unplug type C.
> 
> We are not done yet.
> 
> Next - Second tab the Firmware Upgrade. Get into maskmode - Load firmware.img from openfyde github wait - Then Flash. After its done unplug type C et voilá!! OpenFyde works nay!
> 
> For the fan to work ctrl alt T type Shell then sudo su -u echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/export echo 10000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/period echo 5000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/duty_cycle echo normal > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/polarity echo 1 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable #echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable
> 
> Runs really slow... it should run a bit stronger for heavier duty to cooldown.
> 
> Now known Issues: Bluetooth support is coming on the next patch. -No google apps support yet.
> 

Fixed codes had been pushed. However, we are busy with other critical works. 
The next release needs some time.

> Thanks Damenly.

**Comment by DarkevilPT** [comment]
> > Update > Finally Sort out this ISSUE! FINALLY!! Auff what a relief!
> 
> Wooo!
> 
> > RKDEVTOOLS you guys really need to make it more clearer on how to flash this.
> 
> Right. It's our responsibility. It's pretty awful to waste users' time to fash and disappoint them. The excuse is that most of us use linux tool not Windows RKDEVTOOLS. Anyway, We will make it clearer.
> 
> > My issue was that, because on my first attempt it failed to do the Download Image (tab) I was just doing Firmware Upgrade (Tab) and for some reason it never worked decent.
> > So here it goes and I hope this help the community because I love this!
> 
> Thanks for your detailed steps.
> 
> > At least for some clarity on Windows: RK Dev Tools: https://wiki.radxa.com/Rock5/install/rockchip-flash-tools The files for RK Dev Tools are here: https://wiki.radxa.com/Rock5/install/spi (You need the loader.bin and the Release.img)
> > I suggest everyone to do an SPI update with those files up aiming for the release.img Theres a SPI config file in RKDevTools paste to Swap between EMMC and SPI. SPI requires a SPI BIN file and the IMG file. (both on the links above each for what type of usage you desire in my case EMMC). Release is for a default standard (Do Flash your SPI for a boot in EMMC then Micro SD if nothing then NVME).
> > Before yous say (this has nothing to do with flashing openfyde) well yes but for someone who does a lot of image swapping and to give a fresh install you better reset the boot spi flashing it via emmc right on RKDEVTOOLS or skip this part where the next one was the deal breaker for me.
> > RkDevTools has first a Download Image tab (because for me the first time I have used it / it failed to enter the maskmode I thought the mask mode button on Rock5B was the second button.. it detects something but its not the maskmode. The maskmode button is beside the CPU on a top left corner in line with the type C connector. Meaning that everytime RkDevTools fails u better close it and open (again the windows app) and enter into mask mode again by unplugging and plugging the typeC cable.
> > Here we go: Download Image you will need RK Dev Tool.BIN file (found here https://wiki.radxa.com/Rock5/install/spi) Second file to add is the image.IMG file which will be the OpenFyde OS image from github (Tutorial how to do RkDevTool also here https://wiki.radxa.com/Rock5/install/usb-install-emmc)
> > Check option Write by address then Press run. After done unplug type C.
> > We are not done yet.
> > Next - Second tab the Firmware Upgrade. Get into maskmode - Load firmware.img from openfyde github wait - Then Flash. After its done unplug type C et voilá!! OpenFyde works nay!
> > For the fan to work ctrl alt T type Shell then sudo su -u echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/export echo 10000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/period echo 5000 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/duty_cycle echo normal > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/polarity echo 1 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable #echo 0 > /sys/devices/platform/fd8b0010.pwm/pwm/pwmchip*/pwm0/enable
> > Runs really slow... it should run a bit stronger for heavier duty to cooldown.
> > Now known Issues: Bluetooth support is coming on the next patch. -No google apps support yet.
> 
> Fixed codes had been pushed. However, we are busy with other critical works. The next release needs some time.
> 
> > Thanks Damenly.
> 
> Appreciate your trace.

Yes ! All it needs now is Bluetooth and Google Apps Working ! Gapps.

**Comment by DarkevilPT** [comment]
Damenly... I still can't have bluetooth Audio... this is so annoying..
https://i.ibb.co/KjsKNFH/Screenshot-2023-02-19-14-01-18.png

Can yous push the patch for bluetooth? I want to use open fyde but I can't without audio -.-

**Comment by Damenly** [comment]
I have pushed the patch a month ago. The next version will be landed in this/next week.

**Comment by DarkevilPT** [comment]
🙌🙌🙌 thank you 🙌🙌🙌🙌

**Comment by Damenly** [comment]
I'm uploading the new release image.

To enable fan control:
1. Please follow the guide https://faq.fydeos.com/en/getting-started/shell-access/ to enter the shell and be as root.
2. call `mount -o remount,rw /`
3. cp `/usr/share/rock5b/rock5-fan-control.conf /etc/init/;`
4.  Reboot.

The daemon service will start fan as the strategy defined in `/etc/fan-control.json`. You can change it by doing steps 1 and 2 and then modify the file.

**Comment by DarkevilPT** [comment]
WoW  Damenly you got me on Hype ! 
Whats Project ArcHero? 
Can we finally install Apks on a OpenFydeOS Desktop mode ?

**Comment by Damenly** [comment]
ArcHero is our internal project which is another Andriod 11 container implementation.
You can install apks in this version already.
The final goal is to bring Andriod to all openfyde overlays(if hardware performance permits).

NOTE: It's still in active development. Android apps may crash/hang/reboot at any time. 
It shall not influence other parts of the host in theory.  So use it at your risk.

**Comment by DarkevilPT** [comment]
You are a brutal LEGEND !!! Thank you ! 🍺🍺🍺

**Comment by DarkevilPT** [comment]
Ok after a few hours testing I must say I am impressed!! I can now install google apps and try a bunch of different things.
However Damenly bluetooth is still not working due the fact it needs those:

**A8 Module Bluetooth:**
`sudo su` 
`nano /etc/modprobe.d/blacklist.conf` 
then add these lines somewhere (at the bottom of the file is fine):

```
blacklist pgdrv
blacklist btusb
blacklist btrtl
blacklist btbcm
blacklist btintel
```

Then press Ctrl+X, then Y. 
`sudo apt install bluez` or bluetooth -- not needed to install since latest armbian version
`systemctl status bluetooth` CTRL+ C 
`systemctl start bluetooth` 
Then `reboot` .

I don't know how to do these in gentoo or the shell terminal :1

**Comment by DarkevilPT** [comment]
Issue number 2: Its not a big issue but so it happens that installed apk often turn into chinese on the default language.
Keeps switching between Chinese vs English after a restart or so.

**Comment by Damenly** [comment]
To enable A8 bluetooth:

1. Please follow the guide https://faq.fydeos.com/en/getting-started/shell-access/ to enter the shell and be root.
2. call `mount -o remount,rw /`
3. nano /etc/modprobe.d/blacklist.conf
then add these lines somewhere (at the bottom of the file is fine):
```
blacklist pgdrv
blacklist btusb
blacklist btrtl
blacklist btbcm
blacklist btintel
```
Then press Ctrl+X, then Y.
4. reboot.

**Comment by Damenly** [comment]
> Issue number 2: Its not a big issue but so it happens that installed apk often turn into chinese on the default language. Keeps switching between Chinese vs English after a restart or so.

Noted. Will transfer the feedback to our Android team. Thanks.

**Comment by DarkevilPT** [comment]
[[](url)](https://i.ibb.co/5WSLPvB/Screenshot-2023-03-04-14-24-07.png)

Basically if the installed app doesn't has any language options then standard will be chinese.
Luckily most apps have language in options :D

Audio is working perfect!
